version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --template-file template.yml --s3-bucket nguyenvu-upload-lambda-functions --output-template-file packaged-template.yml
artifacts:
  files:
    - output-package.yaml