AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: 'sam-nodejs-example

  Sample SAM Template for sam-nodejs-example

  '
Globals:
  Function:
    Timeout: 30
    Runtime: nodejs10.x
Resources:
  Upload:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://local-nguyenvu-upload-lambda-functions/3bed4c82583f607af3cdceb96d4e22bd
      Handler: app.handler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
  Analystic:
    Type: AWS::Serverless::Function
    Properties:
<<<<<<< HEAD
      CodeUri: s3://local-nguyenvu-upload-lambda-functions/7ad237f4c530cca5f1ba0dde049df2af
=======
      CodeUri: s3://local-nguyenvu-upload-lambda-functions/37bda899db06be538481362da6dc7482
>>>>>>> 5a45ecf72d60cfc6acf68bd1044d1604814372b4
      Handler: app.analystic
      Runtime: nodejs12.x
      Policies:
      - SNSPublishMessagePolicy:
          TopicName:
            Fn::GetAtt:
            - SNSAnalysisTopic
            - TopicName
<<<<<<< HEAD
      - DynamoDBWritePolicy:
          TableName: BatchJob
=======
>>>>>>> 5a45ecf72d60cfc6acf68bd1044d1604814372b4
      Environment:
        Variables:
          SNS_TOPIC_ANALYSIS_ARN:
            Ref: SNSAnalysisTopic
          DYNAMODB_TableName:
            Fn::GetAtt:
            - DynamoDBTBatchJobTable
            - Arn
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /analystic
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        FileUploaded:
          Type: S3
          Properties:
            Bucket:
              Ref: UploadFile
            Events: s3:ObjectCreated:*
  Transcoder:
    Type: AWS::Serverless::Function
    Properties:
<<<<<<< HEAD
      CodeUri: s3://local-nguyenvu-upload-lambda-functions/9617a5f4b795349bf47d532d6d315c18
      Handler: app.transcoder
      Runtime: nodejs12.x
      Layers:
      - Ref: FFMPEGLAYER
=======
      CodeUri: s3://local-nguyenvu-upload-lambda-functions/358a5f3833e67395c9dbf71474767066
      Handler: app.transcoder
      Runtime: nodejs12.x
>>>>>>> 5a45ecf72d60cfc6acf68bd1044d1604814372b4
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSAnalysisTopic
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowMethods: '''OPTIONS,POST,GET,PATCH'''
        AllowHeaders: '''Content-Type'''
        AllowOrigin: '''*'''
  UploadFile:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: local-task-nguyenvu
  SNSAnalysisTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SNSAnalysisTopic
<<<<<<< HEAD
  SNSJobListTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SNSJobListTopic
  DynamoDBTBatchJobTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: BatchJob
  FFMPEGLAYER:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ffmpeg
      Description: Execution file for ffmpeg
      ContentUri: s3://local-nguyenvu-upload-lambda-functions/ccbd35cf774d964cfe57de274f110e12
      CompatibleRuntimes:
      - nodejs12.x
=======
>>>>>>> 5a45ecf72d60cfc6acf68bd1044d1604814372b4
